time: 2017-10-30 16:35:48.711365Z
tags: worker-1
test: tacker.tests.unit.nfvo.drivers.vim.test_kubernetes_driver.TestKubernetes_Driver.test_deregister_vim_barbican
time: 2017-10-30 16:35:48.728509Z
successful: tacker.tests.unit.nfvo.drivers.vim.test_kubernetes_driver.TestKubernetes_Driver.test_deregister_vim_barbican [ multipart
]
tags: -worker-1
time: 2017-10-30 16:35:48.754482Z
tags: worker-3
test: tacker.tests.unit.nfvo.drivers.vim.test_kubernetes_driver.TestKubernetes_Driver.test_encode_vim_auth_barbican
time: 2017-10-30 16:35:48.768564Z
successful: tacker.tests.unit.nfvo.drivers.vim.test_kubernetes_driver.TestKubernetes_Driver.test_encode_vim_auth_barbican [ multipart
]
tags: -worker-3
time: 2017-10-30 16:35:48.764630Z
tags: worker-0
test: tacker.tests.unit.nfvo.drivers.vim.test_kubernetes_driver.TestKubernetes_Driver.test_register_k8sclient
time: 2017-10-30 16:35:48.789717Z
failure: tacker.tests.unit.nfvo.drivers.vim.test_kubernetes_driver.TestKubernetes_Driver.test_register_k8sclient [ multipart
Content-Type: text/x-traceback;language=python,charset=utf8
traceback
24C
Traceback (most recent call last):
  File "tacker/tests/unit/nfvo/drivers/vim/test_kubernetes_driver.py", line 93, in test_register_k8sclient
    self._test_register_vim(self.vim_obj, mock_ks_client)
  File "tacker/tests/unit/nfvo/drivers/vim/test_kubernetes_driver.py", line 110, in _test_register_vim
    file_mock().write.assert_called_once_with('test_fernet_key')
  File "/opt/stack/tacker/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 947, in assert_called_once_with
    raise AssertionError(msg)
AssertionError: Expected 'write' to be called once. Called 0 times.
0
]
tags: -worker-0
time: 2017-10-30 16:35:48.943154Z
tags: worker-2
test: tacker.tests.unit.nfvo.drivers.vim.test_kubernetes_driver.TestKubernetes_Driver.test_deregister_vim
time: 2017-10-30 16:35:48.955309Z
successful: tacker.tests.unit.nfvo.drivers.vim.test_kubernetes_driver.TestKubernetes_Driver.test_deregister_vim [ multipart
]
tags: -worker-2
